DbUser: "root"
DbPsw : "qweqwe"
DbName : "app_db"
# DbHost: "db-mysql"
DbHost: "127.0.0.1:3307"
AppPort: "3000"

# DbUser: "sql10462371"
# DbPsw : "DBXr6CAvmW"
# DbName : "sql10462371"
# DbHost: "sql10.freemysqlhosting.net:3306"
# # DbHost: "127.0.0.1:3307"
# AppPort: "3000"