version: '3'
 
services:
  mysql:
      image: mysql:5.7
      container_name: db-mysql
      environment:
        - docker.env
      networks:
        - mynet
      ports:
        - "3307:3306"
      volumes:
        - dbdata:/var/lib/mysql
  app:
    container_name: pb-backend
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - mynet
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - docker.env
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  dbdata:
networks:
  mynet:
    driver: bridge