version: '3'
 
services:
  app:
    container_name: pb-backend
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      API_SERVER_ADDR: ":3000"
    networks:
      - mynet
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    deploy:
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:5.7
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qweqwe
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pwd
    networks:
      - mynet
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
networks:
  mynet:
    driver: bridge


#   version: '3'
 
# services:
#   db:
#     image: mysql:5.7
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: my_secret_password
#       MYSQL_DATABASE: app_db
#       MYSQL_USER: db_user
#       MYSQL_PASSWORD: db_user_pass
#     ports:
#       - "6033:3306"
#     volumes:
#       - ./data/db:/var/lib/mysql

