package entities

// Code generated by xo. DO NOT EDIT.

import (
	"context"

	"github.com/elgris/sqrl"
)

// User represents a row from 'user'.
type User struct {
	ID       int    `json:"ID" db:"id"`             // id
	Username string `json:"Username" db:"username"` // username
	Password string `json:"Password" db:"password"` // password
	Email    string `json:"Email" db:"email"`       // email
	Active   bool   `json:"Active" db:"active"`     // active
	// xo fields
	_exists, _deleted bool
}

type FilterUser struct {
	ID       *int    // id
	Username *string // username
	Password *string // password
	Email    *string // email
	Active   *bool   // active

}

// Apply filter to sqrl User .
func (u *User) ApplyFilterSale(sqrlBuilder *sqrl.SelectBuilder, filter FilterUser) bool {
	if filter.ID != nil {
		sqrlBuilder.Where(sqrl.Eq{"id": filter.ID})
	}
	if filter.Username != nil {
		sqrlBuilder.Where(sqrl.Eq{"username": filter.Username})
	}
	if filter.Password != nil {
		sqrlBuilder.Where(sqrl.Eq{"password": filter.Password})
	}
	if filter.Email != nil {
		sqrlBuilder.Where(sqrl.Eq{"email": filter.Email})
	}
	if filter.Active != nil {
		sqrlBuilder.Where(sqrl.Eq{"active": filter.Active})
	}

	return true
}

// Exists returns true when the User exists in the database.
func (u *User) Exists() bool {
	return u._exists
}

// Deleted returns true when the User has been marked for deletion from
// the database.
func (u *User) Deleted() bool {
	return u._deleted
}

// Insert inserts the User to the database.
func (u *User) Insert(ctx context.Context, db DB) error {
	switch {
	case u._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case u._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO user (` +
		`username, password, email, active` +
		`) VALUES (` +
		`?, ?, ?, ?` +
		`)`
	// run
	logf(sqlstr, u.Username, u.Password, u.Email, u.Active)
	res, err := db.ExecContext(ctx, sqlstr, u.Username, u.Password, u.Email, u.Active)
	if err != nil {
		return logerror(err)
	}
	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return logerror(err)
	} // set primary key
	u.ID = int(id)
	// set exists
	u._exists = true
	return nil
}

// Update updates a User in the database.
func (u *User) Update(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case u._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with primary key
	const sqlstr = `UPDATE user SET ` +
		`username = ?, password = ?, email = ?, active = ? ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, u.Username, u.Password, u.Email, u.Active, u.ID)
	if _, err := db.ExecContext(ctx, sqlstr, u.Username, u.Password, u.Email, u.Active, u.ID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the User to the database.
func (u *User) Save(ctx context.Context, db DB) error {
	if u.Exists() {
		return u.Update(ctx, db)
	}
	return u.Insert(ctx, db)
}

// Upsert performs an upsert for User.
func (u *User) Upsert(ctx context.Context, db DB) error {
	switch {
	case u._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO user (` +
		`id, username, password, email, active` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)` +
		` ON DUPLICATE KEY UPDATE ` +
		`username = VALUES(username), password = VALUES(password), email = VALUES(email), active = VALUES(active)`
	// run
	logf(sqlstr, u.ID, u.Username, u.Password, u.Email, u.Active)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID, u.Username, u.Password, u.Email, u.Active); err != nil {
		return logerror(err)
	}
	// set exists
	u._exists = true
	return nil
}

// Delete deletes the User from the database.
func (u *User) Delete(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return nil
	case u._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM user ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, u.ID)
	if _, err := db.ExecContext(ctx, sqlstr, u.ID); err != nil {
		return logerror(err)
	}
	// set deleted
	u._deleted = true
	return nil
}

// UserByEmail retrieves a row from 'user' as a User.
//
// Generated from index 'email'.
func UserByEmail(ctx context.Context, db DB, email string) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, username, password, email, active ` +
		`FROM user ` +
		`WHERE email = ?`
	// run
	logf(sqlstr, email)
	u := User{
		_exists: true,
	}
	qb := sqrl.Expr(sqlstr, email)
	if err := db.QueryRowContext(ctx, &u, qb); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}

// UserByID retrieves a row from 'user' as a User.
//
// Generated from index 'user_id_pkey'.
func UserByID(ctx context.Context, db DB, id int) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, username, password, email, active ` +
		`FROM user ` +
		`WHERE id = ?`
	// run
	logf(sqlstr, id)
	u := User{
		_exists: true,
	}
	qb := sqrl.Expr(sqlstr, id)
	if err := db.QueryRowContext(ctx, &u, qb); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}
