// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Friend struct {
	City *string `json:"City"`
}

type NewUser struct {
	Name string `json:"name"`
}

type Pagination struct {
	PerPage *int     `json:"PerPage"`
	Page    *int     `json:"Page"`
	Sort    []string `json:"Sort"`
}

type UserDto struct {
	ID       int    `json:"id"`
	Token    string `json:"token"`
	Role     string `json:"role"`
	UserName string `json:"userName"`
}
