// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Friend struct {
	City *string `json:"City"`
}

type NewUser struct {
	Name string `json:"name"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	FriendID string `json:"FriendId"`
}
