// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiregen

import (
	"context"
	"github.com/google/wire"
	"pb-backend/db"
	"pb-backend/graph"
	"pb-backend/services"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	db := db_manager.OpenConnectTion()
	userService := &services.UserService{
		DB: db,
	}
	resolver := &graph.Resolver{
		IUserService: userService,
	}
	app := &App{
		Resolver: resolver,
	}
	return app, nil
}

// wire.go:

var serviceSet = wire.NewSet(services.NewUserService)

var dbSet = wire.NewSet(db_manager.OpenConnectTion, wire.Bind(new(db_manager.IDb), new(*db_manager.DB)))

type App struct {
	Resolver *graph.Resolver
}
