// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiregen

import (
	"context"
	"github.com/google/wire"
	"pb-backend/graph"
	"pb-backend/services"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	userService := &services.UserService{}
	resolver := &graph.Resolver{
		IUserService: userService,
	}
	app := &App{
		Resolver: resolver,
	}
	return app, nil
}

// wire.go:

var serviceSet = wire.NewSet(services.NewUserService)

type App struct {
	Resolver *graph.Resolver
}
